# STEP 1 - nodejs build stage

FROM node:12 as builder
    
WORKDIR /home/kodi_rc_client

COPY ./vuejs-client/ /home/kodi_rc_client/

ARG VUE_APP_KODI
ENV VUE_APP_KODI $VUE_APP_KODI

RUN true \
    && npm install \
    && npm run build \
    && true

# STEP 2 - nginx stage

FROM nginx:alpine

LABEL name="KodiRC client" \
      maintainer="d.machard@gmail.com"

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /home/kodi_rc_client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
